const Q=(unit,question,options,answer,note='')=>({unit,question,options,answer,note});
const IP='IP Addressing',OSI='OSI & Addressing',ETH='Ethernet',WIFI='Wireless LAN',MEDIA='Transmission Media',PROTO='Protocols & Scenarios';
window.QUESTION_BANK=[
// IP Addressing & classful networks
Q(IP,'How many usable hosts are available in a Class A network?',['126','16,777,214','254','65,534'],1,'A Class A network has 24 host bits: 2²⁴ − 2 usable hosts.'),
Q(IP,'How many total addresses are in the default block containing 11.22.33.44?',['16,777,214','65,536','16,777,216','256'],2,'11.x.x.x is Class A, so its default block contains 2²⁴ addresses.'),
Q(IP,'Find the classful network ID for 192.168.1.1.',['192.168.0.0','192.168.1.1','192.0.0.0','192.168.1.0'],3,'192.x is Class C; the first three octets identify the network.'),
Q(IP,'Determine the broadcast address for 192.168.1.1 using its default mask.',['192.255.255.255','192.168.1.0','192.168.1.255','192.168.255.255'],2),
Q(IP,'Find the last address of the classful block containing 220.10.10.10.',['220.10.10.255','220.255.255.255','220.10.10.0','220.10.255.255'],0),
Q(IP,'A device has IP 172.16.5.4. How many total IP addresses are in its default network?',['256','65,536','65,534','16,777,216'],1,'172.x is Class B, with 16 host bits.'),
Q(IP,'A company is assigned 150.10.20.5. What is its classful network ID?',['150.10.255.0','150.10.0.0','150.10.20.0','150.0.0.0'],1),
Q(IP,'Find the classful broadcast address of 190.20.30.40.',['190.20.30.255','190.255.255.255','190.20.255.255','190.20.0.255'],2),
Q(IP,'A host uses IP 200.15.10.1. How many total addresses exist in its default block?',['256','65,536','255','254'],0),
Q(IP,'What is the last address in the default block of 200.15.10.1?',['200.255.255.255','200.15.10.255','200.15.255.255','200.15.10.0'],1),
Q(IP,'What is the broadcast address of 192.168.5.64/26?',['192.168.5.64','192.168.5.255','192.168.5.63','192.168.5.127'],3,'A /26 block has 64 addresses: .64 through .127.'),
Q(IP,'How many usable hosts are available in a Class C network?',['256','126','65,534','254'],3),
Q(IP,'What is the last usable host of 10.0.0.0/8?',['10.255.255.255','10.0.0.0','10.255.255.254','10.0.0.1'],2),
Q(IP,'What is the default subnet mask of Class B?',['255.0.0.0','255.255.255.0','255.255.255.255','255.255.0.0'],3),
Q(IP,'IP 130.25.60.1 belongs to a default block containing how many total addresses?',['65,534','256','16,777,216','65,536'],3),
Q(IP,'What is the classful broadcast address of 130.25.60.1?',['130.25.0.255','130.25.255.255','130.25.60.255','130.255.255.255'],1),
Q(IP,'What is the classful network address of 130.25.60.1?',['130.25.255.0','130.25.60.0','130.0.0.0','130.25.0.0'],3),
Q(IP,'How many total addresses are in the default block of 220.10.10.10?',['256','255','65,536','254'],0),
Q(IP,'What is the first usable IP of 192.168.1.0/24?',['192.168.1.1','192.168.1.0','192.168.1.255','192.168.1.254'],0),
Q(IP,'What is the ending address of the classful block containing 10.5.6.7?',['10.5.6.255','10.5.255.255','10.255.255.255','10.0.0.0'],2),
Q(IP,'Find the classful network base address for 172.16.5.4.',['172.16.0.0','172.0.0.0','172.16.255.0','172.16.5.0'],0),
Q(IP,'An organization uses IP 10.5.6.7. How many total addresses are in its default network?',['256','16,777,216','65,536','16,777,214'],1),
Q(IP,'Determine the first address of the classful block containing 220.10.10.10.',['220.10.10.0','220.10.0.0','220.10.10.10','220.0.0.0'],0),
Q(IP,'What is the classful broadcast address for 172.16.5.4?',['172.16.5.255','172.16.255.255','172.16.0.255','172.255.255.255'],1),
Q(IP,'Which class does IP 10.25.67.9 belong to?',['Class C','Class B','Class D','Class A'],3),
Q(IP,'Given IP 150.10.20.5, what is its classful broadcast address?',['150.10.20.255','150.255.255.255','150.10.255.255','150.10.0.255'],2),
Q(IP,'What is the first usable host of 10.0.0.0/8?',['10.255.255.255','10.0.0.1','10.0.0.0','10.255.255.254'],1),
Q(IP,'What is the network identifier of 190.20.30.40?',['190.20.255.0','190.20.0.0','190.20.30.0','190.0.0.0'],1),
Q(IP,'What is the last usable IP of 192.168.1.0/24?',['192.168.1.0','192.168.1.254','192.168.1.255','N/A'],1),
Q(IP,'A PC has IP 192.168.1.1. How many total addresses are in its default network?',['255','256','254','65,536'],1),
Q(IP,'Determine the starting address of the classful block containing 10.5.6.7.',['10.5.0.0','10.0.0.0','10.255.255.255','10.5.6.0'],1),
Q(IP,'Given IP 190.20.30.40, how many total addresses are in its default block?',['65,536','16,777,216','65,534','256'],0),
Q(IP,'How many bits are in an IPv4 address?',['32','64','128','256'],0),
Q(IP,'The IPv4 address space uses _____.',['16 bits','8 bytes','4 bytes','8 bits'],2),

// OSI, layers and address types
Q(OSI,'Which of the following is an example of a logical address?',['192.168.1.1','00:1A:2B:3C:4D:5E','80:00:20:0A:B1:2D','COM1'],0),
Q(OSI,'At which layer is a port address used?',['Data Link','Network','Transport','Physical'],2),
Q(OSI,'A repeater operates only at which OSI layer?',['Application','Physical','Network','Data Link'],1),
Q(OSI,'Which layer moves individual bits from one hop to the next?',['Application','Physical','Data Link','Transport'],1),
Q(OSI,'Delivery of a message from one process to another is the responsibility of which layer?',['Transport','Data Link','Network','Application'],0),
Q(OSI,'Routing is a responsibility of which OSI layer?',['Network','Data Link','Transport','Application'],0),
Q(OSI,'Which of the following is an example of a port number?',['192.168.1.1','255.255.255.0','80','00:1A:2B:3C:4D:5E'],2),
Q(OSI,'The logical address is used at which layer?',['Physical','Data Link','Network','Transport'],2),
Q(OSI,'The physical (MAC) address is used at which layer?',['Physical','Data Link','Network','Transport'],1),
Q(OSI,'Which address identifies a specific process or service on a host?',['IP address','MAC address','Port address','Broadcast address'],2),
Q(OSI,'The network layer delivers individual _____ from source to destination.',['Payloads','Bits','Packets','Frames'],2),
Q(OSI,'Which OSI layer provides end-to-end communication and error recovery?',['Network','Transport','Application','Physical'],1),
Q(OSI,'Which address changes from hop to hop during routed communication?',['Port address','Specific address','Logical address','Physical address'],3,'MAC addresses are rewritten for each local hop; end-to-end IP addresses normally remain.'),
Q(OSI,'Which header does the network layer add to data from upper layers?',['Physical address','Logical address','Service point address','Real address'],1),
Q(OSI,'Moving frames from one hop to another is the responsibility of which layer?',['Data Link','Transport','Physical','Network'],0),
Q(OSI,'The presentation layer is responsible for _____.',['Translation','Encryption','Compression','All of the above'],3),
Q(OSI,'Which layer manages sessions between applications?',['Physical','Session','Network','Data Link'],1),
Q(OSI,'Which layer provides user services such as HTTP?',['Application','Presentation','Transport','Physical'],0),
Q(OSI,'TCP and UDP operate at which layer?',['Application','Transport','Network','Data Link'],1),
Q(OSI,'IP and routing belong primarily to which layer?',['Physical','Data Link','Network','Session'],2),
Q(OSI,'How many layers are in the OSI model?',['4','5','7','8'],2),
Q(OSI,'Which order is correct from lowest to highest OSI layer?',['Physical, Data Link, Network, Transport','Network, Physical, Data Link, Transport','Transport, Network, Physical, Data Link','Data Link, Physical, Transport, Network'],0),
Q(OSI,'Performance, reliability, and security are considered _____.',['Physical layer criteria','Network criteria','Protocol fields','Address types'],1),
Q(OSI,'The frequency of failure is a measure of network _____.',['Performance','Security','Reliability','Availability'],2),
Q(OSI,'Which connection provides a dedicated link between two devices?',['Minimum point','Multipoint','Point-to-point','Broadcast'],2),

// Ethernet and MAC
Q(ETH,'What is the unit of communication at the Physical layer?',['Packet','Frame','Message','Bit'],3),
Q(ETH,'What are the minimum and maximum Ethernet payload sizes?',['64 and 1024 bytes','46 and 2048 bytes','1500 and 2048 bytes','46 and 1500 bytes'],3),
Q(ETH,'What is the main function of a MAC address?',['Encrypt data','Determine IP addresses','Control data flow','Uniquely identify a network interface'],3),
Q(ETH,'What is the speed of Fast Ethernet?',['10 Mbps','10 Gbps','1 Gbps','100 Mbps'],3),
Q(ETH,'An Ethernet source address is always _____.',['Multicast','Anycast','Broadcast','Unicast'],3),
Q(ETH,'Which address is multicast?',['4A:30:10:21:10:1A','49:30:10:21:10:1A','48:30:10:21:10:1A','4C:30:10:21:10:1A'],0,'The least significant bit of the first transmitted octet indicates an individual/group address.'),
Q(ETH,'Which is NOT a function of Ethernet?',['Data transmission','Error detection','Addressing','Routing between networks'],3),
Q(ETH,'How many bytes are in a standard Ethernet MAC address?',['8','10','6','4'],2),
Q(ETH,'What is the Ethernet preamble?',['56 bits of alternating 1s and 0s','6 bytes of zeros','2 bytes of ones','2048 alternating bits'],0),
Q(ETH,'What is the length of the Ethernet preamble field?',['1518 bytes','6 bytes','56 bytes','7 bytes'],3),
Q(ETH,'What is the purpose of the Frame Check Sequence (FCS)?',['Ensure delivery','Encrypt data','Assign priority','Detect errors'],3),
Q(ETH,'What alerts an Ethernet receiver to a coming frame and synchronizes timing?',['CRC','Logical address','SFD','Preamble'],3),
Q(ETH,'What marks the last chance for receiver synchronization immediately after the preamble?',['Source Address','DNS','SFD','Payload'],2),
Q(ETH,'Which device regenerates and retimes the original bit pattern?',['Layer 3 switch','Repeater','Gateway','Layer 2 switch'],1),
Q(ETH,'A bridge works primarily at which layer?',['Data Link','Network','Physical','Application'],0),
Q(ETH,'For 100 Mbps Fast Ethernet, how long does transmitting the minimum 64-byte frame take?',['0.512 μs','5.12 μs','51.2 μs','512 μs'],1,'64 bytes = 512 bits; 512 ÷ 100,000,000 = 5.12 μs.'),

// Wireless LAN
Q(WIFI,'An Extended Service Set (ESS) is made up of _____.',['One BSS with two APs','An ad hoc network','One infrastructure BSS','Two or more BSSs with APs'],3),
Q(WIFI,'When a station sends an RTS frame, it includes the _____ needed to occupy the channel.',['Data size','Number of frames','Duration of time','Number of packets'],2),
Q(WIFI,'An ad hoc wireless network is _____.',['A BSS with an AP','A BSS without an AP','A BSS with two APs','A BSS with three APs'],1),
Q(WIFI,'An infrastructure wireless network is _____.',['A BSS with two APs','A BSS without an AP','A BSS with an AP','A BSS with three APs'],2),
Q(WIFI,'After hearing RTS/CTS duration information, other stations start their _____.',['ACK','NAV timer','FCS','DNS cache'],1),
Q(WIFI,'Why can wireless LANs not reliably use CSMA/CD?',['They have no frames','Hidden stations and difficulty sending/receiving simultaneously','They have no addresses','Wi-Fi never has collisions'],1),
Q(WIFI,'CSMA/CA primarily attempts to _____.',['Detect collisions after sending','Avoid collisions before sending','Encrypt wireless data','Assign IP addresses'],1),
Q(WIFI,'RTS and CTS frames help solve which wireless problem?',['DNS failure','Hidden station problem','Subnet exhaustion','Cable attenuation'],1),
Q(WIFI,'What does NAV stand for?',['Network Address Value','Network Allocation Vector','Node Access Variable','Network ARP Verification'],1),
Q(WIFI,'Which IEEE standard defines wireless LANs?',['IEEE 802.3','IEEE 802.11','IEEE 802.15','IEEE 802.1X only'],1),
Q(WIFI,'Which IEEE 802.11 frame field indicates how long the channel will be reserved?',['Frame Body','Duration','Sequence Control','FCS'],1),
Q(WIFI,'Which wireless frame field maintains frame order?',['Sequence Control','Duration','Frame Body','Preamble'],0),
Q(WIFI,'What happens when FCS detects an erroneous wireless frame?',['It is encrypted','It is dropped and may be retransmitted','Its IP is changed','It becomes an ACK'],1),
Q(WIFI,'Compared with Bluetooth, Wi-Fi generally provides _____.',['Shorter range and lower data rate','Longer range and higher data rate','No internet access','Only device pairing'],1),
Q(WIFI,'Bluetooth is most commonly used for _____.',['Long-range routing','Short-range device pairing','Classful subnetting','Fiber transmission'],1),

// Transmission media and communication basics
Q(MEDIA,'The physical path over which a message travels is called the _____.',['Medium','Protocol','Signal','Simplex'],0),
Q(MEDIA,'Which is NOT a guided transmission medium?',['Fiber-optic cable','Twisted-pair cable','Atmosphere','Coaxial cable'],2),
Q(MEDIA,'In optical fiber, the inner core is _____ the cladding.',['Less dense than','Another name for','The same density as','Denser than'],3),
Q(MEDIA,'Which guided medium is most susceptible to electromagnetic interference?',['Coaxial cable','Fiber-optic cable','Twisted-pair cable','Infrared'],2),
Q(MEDIA,'Which cable is most commonly used in Ethernet networks?',['Coaxial','Twisted-pair','Fiber-optic','Infrared'],1),
Q(MEDIA,'Which medium is not affected by electrical noise?',['Twisted-pair','Coaxial','Infrared','Fiber-optic'],3),
Q(MEDIA,'What makes coaxial cable less susceptible to noise than twisted pair?',['Inner conductor','Cable diameter','Outer conductor/shield','Insulating material'],2),
Q(MEDIA,'Which transmission medium is commonly used in remote controls?',['Fiber-optic','Microwaves','Radio waves','Infrared'],3),
Q(MEDIA,'Single-mode fiber uses _____.',['Many paths and a thick core','One highly focused path and a thin core','Radio waves','Copper conductors'],1),
Q(MEDIA,'How many principal multimode fiber index types are commonly discussed?',['One','Two: step-index and graded-index','Three','Four'],1),
Q(MEDIA,'For a large enterprise with high data demand and long distances, which medium is generally best?',['Twisted pair only','Fiber-optic cable','Infrared','Bluetooth'],1),
Q(MEDIA,'Which is an unguided medium?',['Coaxial cable','Twisted pair','Fiber-optic cable','Wi-Fi radio'],3),
Q(MEDIA,'Communication between a computer and a traditional keyboard is _____.',['Simplex','Half-duplex','Full-duplex','Multipoint'],0),
Q(MEDIA,'Half-duplex allows communication _____.',['In one direction only','Both directions, but not simultaneously','Both directions simultaneously','Only by broadcast'],1),
Q(MEDIA,'Which topology can stop all transmission if its main cable breaks?',['Bus','Star','Mesh','Point-to-point'],0),

// Protocols and scenarios
Q(PROTO,'ARP is primarily used to resolve _____.',['Ports to IP addresses','IP addresses to MAC addresses','MAC addresses to domain names','IP addresses to hostnames'],1),
Q(PROTO,'DNS translates a domain name such as mail.example.com into _____.',['A MAC address','An IP address','A port number','An Ethernet frame'],1),
Q(PROTO,'Which port is traditionally used by SMTP for sending email?',['20','25','53','80'],1),
Q(PROTO,'A client ephemeral port such as 49152 identifies _____.',['The physical cable','A temporary client-side process endpoint','A router MAC','A DNS domain'],1),
Q(PROTO,'During email transmission, which layer adds source and destination port numbers?',['Application','Transport','Network','Data Link'],1),
Q(PROTO,'During email transmission, which layer adds source and destination IP addresses?',['Physical','Transport','Network','Presentation'],2),
Q(PROTO,'On the local network, which layer wraps an IP packet with source and destination MAC addresses?',['Application','Transport','Network','Data Link'],3),
Q(PROTO,'Which address type is used end-to-end for routing across networks?',['Logical/IP address','Physical/MAC address only','FCS','Preamble'],0),
Q(PROTO,'Which address type is used for delivery on the current local network segment?',['Port address only','MAC address','Domain name','Subnet prefix only'],1),
Q(PROTO,'Which five components form a data communication system?',['Sender, receiver, medium, message, protocol','Sender, OSI, medium, message, router','Receiver, DNS, cable, bit, port','Protocol, IP, MAC, FCS, switch'],0),
Q(PROTO,'A protocol defines _____.',['Only what is communicated','What, how, and when data is communicated','Only cable types','Only IP classes'],1),
Q(PROTO,'Which criteria make layered architecture valuable?',['Modularity, interoperability, easier troubleshooting','More collisions','Fewer addresses','Removal of protocols'],0),
Q(PROTO,'For a DNS or IP-related website access problem, which layer is a logical early check?',['Physical only','Network layer','Presentation only','Session only'],1),
Q(PROTO,'Which setup is practical for a temporary outdoor event requiring fast deployment?',['Wi-Fi with a possible wired backup','Only single-mode fiber to every guest','Infrared only','No network'],0),
Q(PROTO,'Which three transport protocols are shown in the TCP/IP layer notes?',['HTTP, DNS, ARP','SCTP, TCP, UDP','IP, ICMP, ARP','Ethernet, Wi-Fi, Bluetooth'],1),
Q(PROTO,'A port address is best described as _____.',['A router path','A network-interface identifier','A process identifier in communication','A LAN hardware address'],2)
];